version: '3.8'

volumes:
  mysql:
    driver: local

services:
  database:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  app:
    build: .
    image: app
    container_name: app
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    links:
      - database
      - rabbitmq
    depends_on:
      - database
      - rabbitmq
